### ISSUE TITLE
课程管理一级入口不显示

### ISSUE THREAD

**Issue by IamMrYao** [open-scratch/teaching#2]
本地搭建完成后admin账号侧边栏没有课程管理和销售一级入口
![水水水水](https://user-images.githubusercontent.com/24777123/82761030-2385ae80-9e2a-11ea-92da-ba57e944a620.png)

**Comment by IamMrYao** [comment]
直接进入  course/course   就直接404了

**Comment by chengyu2333** [comment]
角色管理里配置菜单权限
