### ISSUE TITLE
提几个官方平台小bug

### ISSUE THREAD

**Issue by IamMrYao** [open-scratch/teaching#4]
1.  http://demo.teaching.vip/isystem/user  用户批量生成>点击确定后提示演示模式无法使用；
2.  http://demo.teaching.vip/isystem/user  文件导入>导入成功，但有错误（从导出文件直接修改的xls文件一样无法导入成功）。还有时候出现导入失败，控制台返回token无效（已重新登陆）；
3.  部门管理部分只有第一条有效（初始化系统的第一条部门数据，删掉也不行），新加入的部门信息在选择部门位置不会显示，仅显示第一条，和sys_user_depart有关系。
如果属于非开源功能请忽视，谢谢。

**Comment by chengyu2333** [comment]
演示Demo只有作业部分有写权限，其他只能展示
